name: npm build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: npm install and build
        id: npm_build
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: printable-workitems-${{ github.sha }}
          path: ${{ steps.npm_build.outputs.output_file }}
